"""initial migration

Revision ID: 85a4b0dcefe2
Revises: 
Create Date: 2026-01-18 11:15:57.170437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85a4b0dcefe2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispositivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('localizacao', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispositivos_id'), 'dispositivos', ['id'], unique=False)
    op.create_table('finalidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('base_legal', sa.Enum('CONSENTIMENTO', 'OBRIGACAO_LEGAL', 'EXECUCAO_CONTRATO', 'PROTECAO_VIDA', 'LEGITIMO_INTERESSE', name='baselegal'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_finalidades_id'), 'finalidades', ['id'], unique=False)
    op.create_table('opcoes_tratamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave_politica', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False, comment='Ex: Enviar todos os dados coletados em tempo real.'),
    sa.Column('descricao', sa.String(), nullable=False, comment='Ex: Os dados são coletados a cada 5 segundos e enviados em seguida, sem nenhum tipo de filtro ou tratamento.'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opcoes_tratamento_chave_politica'), 'opcoes_tratamento', ['chave_politica'], unique=True)
    op.create_index(op.f('ix_opcoes_tratamento_id'), 'opcoes_tratamento', ['id'], unique=False)
    op.create_table('tipos_de_dados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_tipos_de_dados_id'), 'tipos_de_dados', ['id'], unique=False)
    op.create_table('titulares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_titulares_email'), 'titulares', ['email'], unique=True)
    op.create_index(op.f('ix_titulares_id'), 'titulares', ['id'], unique=False)
    op.create_table('registros_consentimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'REVOGADO', 'EXPIRADO', name='statusconsentimento'), nullable=False),
    sa.Column('data_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('data_revogacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_expiracao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opcao_tratamento_id', sa.Integer(), nullable=False),
    sa.Column('titular_id', sa.Integer(), nullable=False),
    sa.Column('dispositivo_id', sa.Integer(), nullable=False),
    sa.Column('tipo_de_dado_id', sa.Integer(), nullable=False),
    sa.Column('finalidade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivos.id'], ),
    sa.ForeignKeyConstraint(['finalidade_id'], ['finalidades.id'], ),
    sa.ForeignKeyConstraint(['opcao_tratamento_id'], ['opcoes_tratamento.id'], ),
    sa.ForeignKeyConstraint(['tipo_de_dado_id'], ['tipos_de_dados.id'], ),
    sa.ForeignKeyConstraint(['titular_id'], ['titulares.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registros_consentimento_id'), 'registros_consentimento', ['id'], unique=False)
    op.create_table('logs_auditoria_consentimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('detalhes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['registro_id'], ['registros_consentimento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_auditoria_consentimento_id'), 'logs_auditoria_consentimento', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_auditoria_consentimento_id'), table_name='logs_auditoria_consentimento')
    op.drop_table('logs_auditoria_consentimento')
    op.drop_index(op.f('ix_registros_consentimento_id'), table_name='registros_consentimento')
    op.drop_table('registros_consentimento')
    op.drop_index(op.f('ix_titulares_id'), table_name='titulares')
    op.drop_index(op.f('ix_titulares_email'), table_name='titulares')
    op.drop_table('titulares')
    op.drop_index(op.f('ix_tipos_de_dados_id'), table_name='tipos_de_dados')
    op.drop_table('tipos_de_dados')
    op.drop_index(op.f('ix_opcoes_tratamento_id'), table_name='opcoes_tratamento')
    op.drop_index(op.f('ix_opcoes_tratamento_chave_politica'), table_name='opcoes_tratamento')
    op.drop_table('opcoes_tratamento')
    op.drop_index(op.f('ix_finalidades_id'), table_name='finalidades')
    op.drop_table('finalidades')
    op.drop_index(op.f('ix_dispositivos_id'), table_name='dispositivos')
    op.drop_table('dispositivos')
    # ### end Alembic commands ###
