"""adiciona created_at a finalidades

Revision ID: cd20314d2d5d
Revises: f4d1509c817d
Create Date: 2025-10-14 22:28:59.672359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd20314d2d5d'
down_revision: Union[str, Sequence[str], None] = 'f4d1509c817d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted ###
    op.add_column('finalidades', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted ###
    op.drop_column('finalidades', 'created_at')
    # ### end Alembic commands ###
