"""Adiciona a coluna localizacao a dispositivos

Revision ID: f4d1509c817d
Revises: 
Create Date: 2025-10-09 02:23:30.836394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4d1509c817d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted ###
    op.add_column('dispositivos', sa.Column('localizacao', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted ###
    op.drop_column('dispositivos', 'localizacao')
    # ### end Alembic commands ###